### ISSUE TITLE
Problems when Posting Ads form FinTipOffer Admin

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#71]
When Posting ads on the Behalves of Shop Owner By Admin 
1. There are no alerts displayed on the Android App.
2. The E mail Message Should be changed

FROM

New Ad Added by Tom Thomas 
Details are:
...
...

TO

New Ad Posted by FinTipOffer Admin On the Behalves of shop name: Adams Infotech
Details:
..
..

Please Correct these ..

Please be carefull when you do this as most of the features are working now..

Tom

**Comment by thomastom99** [comment]
One more problem...
When Posting form Admin and if the Date is above the limit , it will display a message . That is fine.. But If we still add the post after correcting the date without Browsing the image again.. The webpage will crash.. Pl check

**Comment by thomastom99** [comment]
Added One more offer form Admin .. Pt displayed alert after 30 min.. Did you updated the web site?..

Also posted one ad from mobile and waiting for alert in the same mobile..

**Comment by thomastom99** [comment]
One thing noticed .. the contact number is not saving the next time it opens after successful posting of offers..

**Comment by thomastom99** [comment]
Didnt get the alert when posted form Mobile although it display on serach option..

**Comment by thomastom99** [comment]
Got alert on another mobile when I post it from my mobile. So I belive offer alert is working correctly.. Didnt checkedd with preferences.. Will check that too soon..

**Comment by thomastom99** [comment]
Preferences with District Option is also working.. Will check the preferences with Town..

**Comment by thomastom99** [comment]
Preferences with twon is also working.. So most of the features realed to alert is working.. So closing this bug for now..

**Comment by manu-mt** [comment]
Fixed

**Comment by thomastom99** [comment]
This message still not modified as per Github Bug description

From: FinTipOffers [mailto:info@xdfthr.in] 
Sent: 25 March 2016 09:45
To: tom.thomas@ktsdftgech.com
Subject: New offerad added

New Ad Added by Tom Thomas 
Details are:
shop name: Adams Infotech
Email id: tom.thomas@ktsinfotech.com
Ad title: Test From Admin Panel
Ad start date:3/25/2016 12:00:00 AM
Ad Expiry date: 4/6/2016 11:59:59 PM
Ad Category: Software

**Comment by thomastom99** [comment]
The E Mail Title show be "New Offer ad Posted"

**Comment by thomastom99** [comment]
Fixed
